version: "3.8"

services:
  member-service:
    build: ./member-management
    ports:
      - "8000:8000"

  subscription-service:
    build: ./subscription-management
    ports:
      - "50051:50051"

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"

  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  payment-service:
    build: ./payment-management
    container_name: payment-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/paymentdb
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin 

  web-bff:
    build: ./web-bff
    container_name: web-bff
    depends_on:
      - member-service
      - payment-service
    ports:
      - "3000:3000"

  mobile-bff:
    build: ./mobile-bff
    container_name: mobile-bff
    depends_on:
      - member-service
      - payment-service
    ports:
      - "8002:8001"

  frontend-shell:
    build: ./frontend-shell
    container_name: frontend-shell
    ports:
      - "4173:80"

  member-frontend:
    build: ./member-frontend
    container_name: member-frontend
    ports:
      - "4174:80"

  subscription-frontend:
    build: ./subscription-frontend
    container_name: subscription-frontend
    ports:
      - "4175:80"

  payment-frontend:
    build: ./payment-frontend
    container_name: payment-frontend
    ports:
      - "4176:80"

volumes:
  postgres_data:


  