name: Run Tests

on: [push]

jobs:

  python-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r member-management/requirements.txt

      - name: Run tests
        run: |
          cd member-management
          pytest


  node-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd subscription-management
          npm install

      - name: Run tests
        run: |
          cd subscription-management
          npm test
    